### ISSUE TITLE
Installation error trying to run the example project

### ISSUE THREAD

**Issue by Alvcosta** [Gimly-Blockchain/gimly-ssi-nfc-react-native#1]
Hello,

I am facing an error when trying the run the example application. I am trying to run the following commands with no success:

```
cd example
yarn install
yarn android
```

However, the yarn build failed. Here is the error log in detail:
```
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

    at makeError (/Users/main/Project/test/gimly-ssi-nfc-react-native/example/node_modules/execa/index.js:174:9)
    at /Users/main/Project/test/gimly-ssi-nfc-react-native/example/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/main/Project/test/gimly-ssi-nfc-react-native/example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/main/Project/test/gimly-ssi-nfc-react-native/example/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
```

About my environment I am on:

```
Mac 12.6.3
Android version 10
node v16.14.0
```

Thank you in advance.

**Comment by cfontana0** [comment]
Hello Alvcosta,

Regarding your issue, our team has been working on some updates in the app including a few changes to the Gradle configuration for the project. 

You must follow an additional step to install the app. First, you need to install the base SDK before installing the example app. If you download the newer version of the library, there is a new command that installs the example app easily for you:

```
yarn install-example
```

Also, the readme now has more information about the installation & running of the example app.

Have a good day.
